filetype: git-config

detect: 
    filename: "git(config|modules)$|\\.git/config$"

rules:
    - constant.bool.true: "\\btrue\\b"
    - constant.bool.false: "\\bfalse\\b"
    - statement: "^[[:space:]]*[^=]*="
    - constant: "^[[:space:]]*\\[.*\\]$"
    - constant.string: "\"(\\\\.|[^\"])*\"|'(\\\\.|[^'])*'"
    - comment: "(^|[[:space:]])#([^{].*)?$"
